

version: '3.8'

services:
  private-element:
    image: ${IMAGE_URL}
    build:
      context: .
    container_name: ${CONTAINER}
    restart: unless-stopped
    env_file:
      - ".env.local.yml"
    ports:
      - ${TARGET_LOCAL_PORT}:${TARGET_REMOTE_PORT}
