

version: '3.8'

services:
  sprinkler:
    image: ${IMAGE_URL}
    build:
      context: .
    container_name: ${CONTAINER}
    restart: unless-stopped
    env_file:
      - ".env.local.yml"
    ports:
      - 0.0.0.0:${TARGET_LOCAL_PORT}:${TARGET_REMOTE_PORT}
